### ISSUE TITLE
Installing Atmel Studio

### ISSUE THREAD

**Issue by ADKaster** [ProjectKarman/avionics-firmware#5]
Atmel Studio 7 can be downloaded from here: http://www.atmel.com/tools/ATMELSTUDIO.aspx

I made this issue because I found that I couldn't open the master project branch on my Windows 8 laptop. The cause was Visual Studio 2015 Update 1, which apparently updates some DLL file that Atmel Studio uses. Long story short, if anyone else has this issue, the workaround is here: 

http://atmel.force.com/support/articles/en_US/Workaround/Installing-Visual-Studio-2015-Update-1-leads-to-Atmel-Studio-no-longer-starting

If anyone has a better place for this, feel free to move it wherever seems appropriate.

**Comment by tkindy** [comment]
Moved information to the README.
