### ISSUE TITLE
Make Git Issues for all Software Items

### ISSUE THREAD

**Issue by brycedcarter** [ProjectKarman/avionics-firmware#6]
Make them even for the mostly completed ones and tag them as testing items

**Comment by tym0027** [comment]
Hey everyone,

Brendan says his work is good to go. And he is writing up a user manual of sorts on how to use it. We should focus some of our next meeting on developing a test case for this driver and task.

I will add more issues as I learn them in the next 24 hours before our meeting.

Tym0027

**Comment by nixpulvis** [comment]
Still need to open issues for everything left to do. Even if they are really high level descriptions.
