### ISSUE TITLE
Test bdowney gryoscope task

### ISSUE THREAD

**Issue by tym0027** [ProjectKarman/avionics-firmware#8]
This task is complete and Brendan is completing a user guide for it. That will be posted when it is available.

For reference,

See task l3g4200d-atxmega128abu

We need to develop a test case for making sure the software meets all functionality requirements.

That also entails testing the ability for this task to run on the development boards.

**Comment by gregwallan** [comment]
Assign Anson

**Comment by brycedcarter** [comment]
### Anson assigned

**Comment by brycedcarter** [comment]
https://db.tt/LR6u11Zu
